# Use the official Node.js image as the base image
FROM node:18.19.1

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application for production
RUN npm run build

# Serve the production build
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "5173"]

EXPOSE 5173