# Use the official Node.js image as the base image
FROM node:22

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Clear npm cache and remove existing node_modules and package-lock.json
RUN npm cache clean --force && \
    rm -rf node_modules package-lock.json

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Create scripts directory and copy install-rollup.js
RUN mkdir -p scripts
COPY scripts/install-rollup.js scripts/

# Build the application for production
RUN npm run build

# Serve the production build
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

EXPOSE 5173