services:
  web:
    build: ./hunspell_live_backend
    command: >
      sh -c "
        while ! nc -z db 5432; do
          echo 'Waiting for database...'
          sleep 1
        done
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./dicts_config/default_dicts_config.json:/code/dicts_config/default_dicts_config.json
      - ./hunspell_live_backend:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0

  frontend:
    build: ./hunspell_live_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./hunspell_live_frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: >
      sh -c "npm install &&
             npm run dev -- --host 0.0.0.0"

  db:
    image: postgres:13
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user -d django_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  pgdata:
