[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && gunicorn --bind 0.0.0.0:8080 core.wsgi:application"
restartPolicyType = "on_failure"
healthcheckPath = "/health/"
healthcheckTimeout = 300

[env]
RAILWAY_ENVIRONMENT = "production"
DJANGO_DEBUG = "False"