[build]
builder = "nixpacks"
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
startCommand = "gunicorn core.wsgi:application"
healthcheckPath = "/health/"
restartPolicyType = "on_failure"
healthcheckTimeout = 75

[env]
RAILWAY_ENVIRONMENT = "production"
DJANGO_DEBUG = "False"
PORT="8000"