[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py collectstatic --noinput && gunicorn core.wsgi:application"
healthcheckPath = "/health/"
restartPolicyType = "on_failure"
healthcheckTimeout = 75

[env]
RAILWAY_ENVIRONMENT = "production"
DJANGO_DEBUG = "False"
PORT="8000"