export const styles = {
  container: {
    height: "100vh",
    minHeight: "100vh",
    width: "1200px",
    padding: "30px 0",
    position: "relative" as const,
    overflow: "hidden",
  },
  content: {
    maxWidth: "1100px",
    height: "calc(100vh - 64px)",
    margin: "0 auto",
    padding: "0 24px",
    display: "flex",
    flexDirection: "column" as const,
    overflow: "visible",
  },
  title: {
    fontSize: "48px",
    fontWeight: "700",
    textAlign: "center",
    marginTop: "10px",
    marginBottom: "20px",
    color: "#1a1a1a",
    letterSpacing: "-0.02em",
    fontFamily: "'Poppins', sans-serif",
    background: "linear-gradient(45deg, #4F46E5, #10B981)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    textShadow: "2px 2px 4px rgba(0, 0, 0, 0.1)",
    position: "relative",
    display: "inline-block",
    padding: "0 20px 8px",
    "&::before": {
      content: '""',
      position: "absolute",
      bottom: "0px",
      left: "0",
      width: "100%",
      height: "4px",
      background: "linear-gradient(45deg, #4F46E5, #10B981)",
      borderRadius: "2px",
    },
  },
  editor: {
    border: "1.5px solid black",
    borderRadius: "12px",
    marginTop: "16px",
    marginBottom: "48px",
    padding: "14px",
    fontSize: "24px",
    fontFamily: "'Noto Sans', system-ui, -apple-system, sans-serif",
    flex: "1 1 auto",
    minHeight: "350px",
    maxHeight: "calc(100vh - 440px)",
    overflowY: "auto",
    backgroundColor: "#ffffff",
    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
    transition: "all 0.2s ease",
    lineHeight: "1.8",
    "&:focus": {
      borderColor: "#3b82f6",
      outline: "none",
    },
  },
  checkButton: {
    backgroundColor: "#3b82f6",
    color: "white",
    padding: "16px 32px",
    fontSize: "18px",
    fontWeight: "600",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s ease",
    "&:active": {
      transform: "translateY(0)",
    },
    marginTop: "0",
    marginBottom: "32px",
    position: "sticky" as const,
    bottom: "0",
    zIndex: 1,
  },
  clearButton: {
    backgroundColor: "white",
    color: "#ef4444",
    border: "#ef4444 1px solid",
    borderRadius: "6px",
    padding: "10px 12px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "16px",
    transition: "all 0.2s ease-in-out",
  },
  pasteButton: {
    backgroundColor: "white",
    color: "#3b82f6",
    border: "#3b82f6 1px solid",
    borderRadius: "6px",
    padding: "10px 12px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "16px",
    transition: "all 0.2s ease-in-out",
  },
  controlsContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "8px",
    width: "100%",
  },
  buttonGroup: {
    display: "flex",
    gap: "8px",
  },
  dropdownContainer: {
    marginLeft: "auto",
    position: "relative",
    zIndex: 10,
    marginTop: "10px",
  },
} as const; 