export const LANGUAGE_OPTIONS = [
  { label: "Afrikaans", value: "af_ZA" },
  { label: "Akan", value: "ak_GH" },
  { label: "Albanian", value: "sq_AL" },
  { label: "Amharic", value: "am_ET" },
  { label: "Arabic (Moz)", value: "ar-moz" },
  { label: "Arabic (Ooe)", value: "ar-ooe" },
  { label: "Arabic (Ooe-2)", value: "ar-ooe-2" },
  { label: "Aragonese", value: "an_ES" },
  { label: "Armenian", value: "hy_AM" },
  { label: "Azerbaijani (Latin)", value: "az_AZ-latin" },
  { label: "Basque", value: "eu" },
  { label: "Belarusian", value: "be" },
  { label: "Belarusian (BY)", value: "be_BY" },
  { label: "Belarusian (Classic)", value: "be_classic" },
  { label: "Bengali", value: "bn_BD" },
  { label: "Breton", value: "br_FR" },
  { label: "Bulgarian", value: "bg_BG" },
  { label: "Burmese", value: "my_MW" },
  { label: "Catalan", value: "ca_ES" },
  { label: "Catalan (Valencia)", value: "ca_ES_valencia" },
  { label: "Coptic", value: "cop_EG" },
  { label: "Croatian", value: "hr_HR" },
  { label: "Czech", value: "cs" },
  { label: "Danish", value: "da_DK" },
  { label: "Dutch", value: "nl_NL" },
  { label: "English (Australia)", value: "en_AU" },
  { label: "English (Australia, Moz)", value: "en_AU-moz" },
  { label: "English (Canada)", value: "en_CA" },
  { label: "English (New Zealand)", value: "en_NZ" },
  { label: "English (South Africa)", value: "en_ZA" },
  { label: "English (UK)", value: "en_GB" },
  { label: "English (US)", value: "en_US" },
  { label: "Esperanto", value: "eo_EO" },
  { label: "Estonian", value: "et_EE" },
  { label: "Faroese", value: "fo_FO" },
  { label: "French", value: "fr" },
  { label: "Frisian", value: "fy_NL" },
  { label: "Friulian", value: "fur_IT" },
  { label: "Galician", value: "gl" },
  { label: "Gascon", value: "gsc_FR" },
  { label: "German (Austria)", value: "de_AT" },
  { label: "German (Austria, Frami Ooe)", value: "de_AT_frami-ooe" },
  { label: "German (Austria, Frami)", value: "de_AT_frami" },
  { label: "German (Germany)", value: "de_DE" },
  { label: "German (Germany, 1901 Ooe)", value: "de_DE-1901-ooe" },
  { label: "German (Germany, 1901)", value: "de_DE-1901" },
  { label: "German (Germany, Frami Ooe)", value: "de_DE_frami-ooe" },
  { label: "German (Germany, Moz)", value: "de_DE-moz" },
  { label: "German (Switzerland)", value: "de_CH" },
  { label: "German (Switzerland, Frami Ooe)", value: "de_CH_frami-ooe" },
  { label: "German (Switzerland, Frami)", value: "de_CH_frami" },
  { label: "German (Switzerland, Moz)", value: "de_CH-moz" },
  { label: "Greek", value: "el_GR" },
  { label: "Greek (Ooe)", value: "el_GR-ooe" },
  { label: "Gujarati", value: "gu_IN" },
  { label: "Hausa", value: "ha_GH" },
  { label: "Hebrew", value: "he_IL" },
  { label: "Hebrew (Moz)", value: "he_IL-moz" },
  { label: "Hebrew (Ooe)", value: "he_IL-ooe" },
  { label: "Hindi", value: "hi_IN" },
  { label: "Hungarian", value: "hu" },
  { label: "Icelandic", value: "is" },
  { label: "Indonesian", value: "id_ID" },
  { label: "Interlingua", value: "ia_ANY" },
  { label: "Irish", value: "ga_IE" },
  { label: "Italian", value: "it_IT" },
  { label: "Italian (Moz)", value: "it_IT-moz" },
  { label: "Italian (Ooe)", value: "it_IT-ooe" },
  { label: "Kannada", value: "kn_ID" },
  { label: "Kashubian", value: "csb_PL" },
  { label: "Kazakh", value: "kk" },
  { label: "Korean", value: "ko" },
  { label: "Kurdish", value: "ku_TR" },
  { label: "Latin (Ooe)", value: "la-ooe" },
  { label: "Latvian", value: "lv" },
  { label: "Lingala", value: "ln_CD" },
  { label: "Lithuanian", value: "lt" },
  { label: "Lower Sorbian", value: "dsb" },
  { label: "Malagasy", value: "mg_MG" },
  { label: "Malay", value: "ms_MY" },
  { label: "Maori", value: "mi_NZ" },
  { label: "Marathi", value: "mr_IN" },
  { label: "Marathi (Moz)", value: "mr_IN-moz" },
  { label: "Nepali", value: "ne_NP" },
  { label: "Norwegian Bokmål", value: "nb_NO" },
  { label: "Norwegian Nynorsk", value: "nn_NO" },
  { label: "Occitan", value: "oc_FR" },
  { label: "Odia", value: "or_IN" },
  { label: "Papiamento", value: "pap_AW" },
  { label: "Papiamento", value: "pap_CW" },
  { label: "Polish", value: "pl" },
  { label: "Portuguese (Brazil)", value: "pt_BR" },
  { label: "Portuguese (Portugal)", value: "pt_PT" },
  { label: "Punjabi", value: "pa_IN" },
  { label: "Romanian", value: "ro_RO" },
  { label: "Romanian (Classic)", value: "ro_RO-classic" },
  { label: "Russian", value: "ru" },
  { label: "Sample Language", value: "sample" },
  { label: "Sanskrit", value: "sa_IN" },
  { label: "Scottish Gaelic", value: "gd_GB" },
  { label: "Slovak", value: "sk" },
  { label: "Slovenian (Ooe)", value: "sl_SI-ooe" },
  { label: "Spanish (Argentina)", value: "es_AR" },
  { label: "Spanish (Argentina, Moz)", value: "es_AR-moz" },
  { label: "Spanish (Bolivia)", value: "es_BO" },
  { label: "Spanish (Chile)", value: "es_CL" },
  { label: "Spanish (Colombia)", value: "es_CO" },
  { label: "Spanish (Costa Rica)", value: "es_CR" },
  { label: "Spanish (Cuba)", value: "es_CU" },
  { label: "Spanish (Dominican Republic)", value: "es_DO" },
  { label: "Spanish (Ecuador)", value: "es_EC" },
  { label: "Spanish (El Salvador)", value: "es_SV" },
  { label: "Spanish (Guatemala)", value: "es_GT" },
  { label: "Spanish (Honduras)", value: "es_HN" },
  { label: "Spanish (Mexico)", value: "es_MX" },
  { label: "Spanish (Mexico, Moz)", value: "es_MX-moz" },
  { label: "Spanish (Nicaragua)", value: "es_NI" },
  { label: "Spanish (Panama)", value: "es_PA" },
  { label: "Spanish (Paraguay)", value: "es_PY" },
  { label: "Spanish (Peru)", value: "es_PE" },
  { label: "Spanish (Puerto Rico)", value: "es_PR" },
  { label: "Spanish (Spain)", value: "es_ES" },
  { label: "Spanish (Spain, Moz)", value: "es_ES-moz" },
  { label: "Spanish (Uruguay)", value: "es_UY" },
  { label: "Spanish (Venezuela)", value: "es_VE" },
  { label: "Spanish (Venezuela, Moz)", value: "es_VE-moz" },
  { label: "Swahili", value: "sw" },
  { label: "Swedish", value: "sv_SE" },
  { label: "Tajik", value: "tg" },
  { label: "Tamil", value: "ta_TA" },
  { label: "Telugu", value: "te_IN" },
  { label: "Ukrainian", value: "uk" },
  { label: "Upper Sorbian", value: "hsb" },
  { label: "Welsh", value: "cy_GB" },
  { label: "Zulu", value: "zu_ZA" }
] as const;

export const LANGUAGE_CODE_MAP: Record<string, string> = {
  af_ZA: 'af_ZA',
  ak_GH: 'ak_GH',
  am_ET: 'am_ET',
  an_ES: 'an_ES',
  'ar-moz': 'ar-moz',
  'ar-ooe': 'ar-ooe',
  'ar-ooe-2': 'ar-ooe-2',
  'az_AZ-latin': 'az_AZ-latin',
  be: 'be',
  be_BY: 'be_BY',
  be_classic: 'be_classic',
  bg_BG: 'bg_BG',
  bn_BD: 'bn_BD',
  br_FR: 'br_FR',
  ca_ES: 'ca_ES',
  ca_ES_valencia: 'ca_ES_valencia',
  cop_EG: 'cop_EG',
  cs: 'cs',
  csb_PL: 'csb_PL',
  cy_GB: 'cy_GB',
  da_DK: 'da_DK',
  de_AT: 'de_AT',
  de_AT_frami: 'de_AT_frami',
  'de_AT_frami-ooe': 'de_AT_frami-ooe',
  de_CH: 'de_CH',
  de_CH_frami: 'de_CH_frami',
  'de_CH_frami-ooe': 'de_CH_frami-ooe',
  'de_CH-moz': 'de_CH-moz',
  de_DE: 'de_DE',
  'de_DE_frami-ooe': 'de_DE_frami-ooe',
  'de_DE-1901': 'de_DE-1901',
  'de_DE-1901-ooe': 'de_DE-1901-ooe',
  'de_DE-moz': 'de_DE-moz',
  dsb: 'dsb',
  el_GR: 'el_GR',
  'el_GR-ooe': 'el_GR-ooe',
  en_AU: 'en_AU',
  'en_AU-moz': 'en_AU-moz',
  en_CA: 'en_CA',
  en_GB: 'en_GB',
  en_NZ: 'en_NZ',
  en_US: 'en_US',
  en_ZA: 'en_ZA',
  eo_EO: 'eo_EO',
  es_AR: 'es_AR',
  'es_AR-moz': 'es_AR-moz',
  es_BO: 'es_BO',
  es_CL: 'es_CL',
  es_CO: 'es_CO',
  es_CR: 'es_CR',
  es_CU: 'es_CU',
  es_DO: 'es_DO',
  es_EC: 'es_EC',
  es_ES: 'es_ES',
  'es_ES-moz': 'es_ES-moz',
  es_GT: 'es_GT',
  es_HN: 'es_HN',
  es_MX: 'es_MX',
  'es_MX-moz': 'es_MX-moz',
  es_NI: 'es_NI',
  es_PA: 'es_PA',
  es_PE: 'es_PE',
  es_PR: 'es_PR',
  es_PY: 'es_PY',
  es_SV: 'es_SV',
  es_UY: 'es_UY',
  es_VE: 'es_VE',
  'es_VE-moz': 'es_VE-moz',
  et_EE: 'et_EE',
  eu: 'eu',
  fo_FO: 'fo_FO',
  fr: 'fr',
  fur_IT: 'fur_IT',
  fy_NL: 'fy_NL',
  ga_IE: 'ga_IE',
  gd_GB: 'gd_GB',
  gl: 'gl',
  gsc_FR: 'gsc_FR',
  gu_IN: 'gu_IN',
  ha_GH: 'ha_GH',
  he_IL: 'he_IL',
  'he_IL-moz': 'he_IL-moz',
  'he_IL-ooe': 'he_IL-ooe',
  hi_IN: 'hi_IN',
  hr_HR: 'hr_HR',
  hsb: 'hsb',
  hu: 'hu',
  hy_AM: 'hy_AM',
  ia_ANY: 'ia_ANY',
  id_ID: 'id_ID',
  is: 'is',
  it_IT: 'it_IT',
  'it_IT-moz': 'it_IT-moz',
  'it_IT-ooe': 'it_IT-ooe',
  kk: 'kk',
  kn_ID: 'kn_ID',
  ko: 'ko',
  ku_TR: 'ku_TR',
  'la-ooe': 'la-ooe',
  ln_CD: 'ln_CD',
  lt: 'lt',
  lv: 'lv',
  mg_MG: 'mg_MG',
  mi_NZ: 'mi_NZ',
  mr_IN: 'mr_IN',
  'mr_IN-moz': 'mr_IN-moz',
  ms_MY: 'ms_MY',
  my_MW: 'my_MW',
  nb_NO: 'nb_NO',
  ne_NP: 'ne_NP',
  nl_NL: 'nl_NL',
  nn_NO: 'nn_NO',
  oc_FR: 'oc_FR',
  or_IN: 'or_IN',
  pa_IN: 'pa_IN',
  pap_AW: 'pap_AW',
  pap_CW: 'pap_CW',
  pl: 'pl',
  pt_BR: 'pt_BR',
  pt_PT: 'pt_PT',
  ro_RO: 'ro_RO',
  'ro_RO-classic': 'ro_RO-classic',
  ru: 'ru',
  sa_IN: 'sa_IN',
  sk: 'sk',
  'sl_SI-ooe': 'sl_SI-ooe',
  sq_AL: 'sq_AL',
  sv_SE: 'sv_SE',
  sw: 'sw',
  ta_TA: 'ta_TA',
  te_IN: 'te_IN',
  tg: 'tg',
  uk: 'uk',
  zu_ZA: 'zu_ZA',
  sample: 'sample'
};

export const TEXT_DIRECTION_MAP: Record<string, 'ltr' | 'rtl'> = {
  af_ZA: 'ltr',
  ak_GH: 'ltr',
  am_ET: 'ltr',
  an_ES: 'ltr',
  'ar-moz': 'rtl',
  'ar-ooe': 'rtl',
  'ar-ooe-2': 'rtl',
  'az_AZ-latin': 'ltr',
  be: 'ltr',
  be_BY: 'ltr',
  be_classic: 'ltr',
  bg_BG: 'ltr',
  bn_BD: 'ltr',
  br_FR: 'ltr',
  ca_ES: 'ltr',
  ca_ES_valencia: 'ltr',
  cop_EG: 'ltr',
  cs: 'ltr',
  csb_PL: 'ltr',
  cy_GB: 'ltr',
  da_DK: 'ltr',
  de_AT: 'ltr',
  de_AT_frami: 'ltr',
  'de_AT_frami-ooe': 'ltr',
  de_CH: 'ltr',
  de_CH_frami: 'ltr',
  'de_CH_frami-ooe': 'ltr',
  'de_CH-moz': 'ltr',
  de_DE: 'ltr',
  'de_DE_frami-ooe': 'ltr',
  'de_DE-1901': 'ltr',
  'de_DE-1901-ooe': 'ltr',
  'de_DE-moz': 'ltr',
  dsb: 'ltr',
  el_GR: 'ltr',
  'el_GR-ooe': 'ltr',
  en_AU: 'ltr',
  'en_AU-moz': 'ltr',
  en_CA: 'ltr',
  en_GB: 'ltr',
  en_NZ: 'ltr',
  en_US: 'ltr',
  en_ZA: 'ltr',
  eo_EO: 'ltr',
  es_AR: 'ltr',
  'es_AR-moz': 'ltr',
  es_BO: 'ltr',
  es_CL: 'ltr',
  es_CO: 'ltr',
  es_CR: 'ltr',
  es_CU: 'ltr',
  es_DO: 'ltr',
  es_EC: 'ltr',
  es_ES: 'ltr',
  'es_ES-moz': 'ltr',
  es_GT: 'ltr',
  es_HN: 'ltr',
  es_MX: 'ltr',
  'es_MX-moz': 'ltr',
  es_NI: 'ltr',
  es_PA: 'ltr',
  es_PE: 'ltr',
  es_PR: 'ltr',
  es_PY: 'ltr',
  es_SV: 'ltr',
  es_UY: 'ltr',
  es_VE: 'ltr',
  'es_VE-moz': 'ltr',
  et_EE: 'ltr',
  eu: 'ltr',
  fo_FO: 'ltr',
  fr: 'ltr',
  fur_IT: 'ltr',
  fy_NL: 'ltr',
  ga_IE: 'ltr',
  gd_GB: 'ltr',
  gl: 'ltr',
  gsc_FR: 'ltr',
  gu_IN: 'ltr',
  ha_GH: 'ltr',
  he_IL: 'rtl',
  'he_IL-moz': 'rtl',
  'he_IL-ooe': 'rtl',
  hi_IN: 'ltr',
  hr_HR: 'ltr',
  hsb: 'ltr',
  hu: 'ltr',
  hy_AM: 'ltr',
  ia_ANY: 'ltr',
  id_ID: 'ltr',
  is: 'ltr',
  it_IT: 'ltr',
  'it_IT-moz': 'ltr',
  'it_IT-ooe': 'ltr',
  kk: 'ltr',
  kn_ID: 'ltr',
  ko: 'ltr',
  ku_TR: 'ltr',
  'la-ooe': 'ltr',
  ln_CD: 'ltr',
  lt: 'ltr',
  lv: 'ltr',
  mg_MG: 'ltr',
  mi_NZ: 'ltr',
  mr_IN: 'ltr',
  'mr_IN-moz': 'ltr',
  ms_MY: 'ltr',
  my_MW: 'ltr',
  nb_NO: 'ltr',
  ne_NP: 'ltr',
  nl_NL: 'ltr',
  nn_NO: 'ltr',
  oc_FR: 'ltr',
  or_IN: 'ltr',
  pa_IN: 'ltr',
  pap_AW: 'ltr',
  pap_CW: 'ltr',
  pl: 'ltr',
  pt_BR: 'ltr',
  pt_PT: 'ltr',
  ro_RO: 'ltr',
  'ro_RO-classic': 'ltr',
  ru: 'ltr',
  sa_IN: 'ltr',
  sk: 'ltr',
  'sl_SI-ooe': 'ltr',
  sq_AL: 'ltr',
  sv_SE: 'ltr',
  sw: 'ltr',
  ta_TA: 'ltr',
  te_IN: 'ltr',
  tg: 'ltr',
  uk: 'ltr',
  zu_ZA: 'ltr',
  sample: 'ltr'
};
