# Generated by Django 5.0.6 on 2024-12-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_profile_currently_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, choices=[('NO', 'high_school_or_less'), ('CO', 'college'), ('BS', 'bachelor'), ('GR', 'graduate')], max_length=3),
        ),
    ]
