# Generated by Django 3.2.25 on 2024-11-24 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hunspell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldictionary',
            name='word_type',
            field=models.CharField(choices=[('dictionary', 'Dictionary'), ('starlist', 'Star List')], default='dictionary', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='personaldictionary',
            unique_together={('user', 'word', 'lang_code', 'word_type')},
        ),
    ]
