# Generated by Django 3.2.25 on 2024-11-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunspell', '0002_auto_20241124_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_word', models.CharField(max_length=100)),
                ('replacement_word', models.CharField(max_length=100)),
                ('lang_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
