export const styles = {
  container: {
    height: "100vh",
    minHeight: "100vh",
    width: "1200px",
    padding: "10px 0",
    position: "relative" as const,
    overflow: "hidden",
  },
  content: {
    maxWidth: "1100px",
    height: "calc(100vh - 64px)",
    margin: "0 auto",
    padding: "0 24px",
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
  },
  title: {
    fontSize: "48px",
    fontWeight: "700",
    textAlign: "center",
    marginBottom: "20px",
    color: "#1a1a1a",
    letterSpacing: "-0.02em",
  },
  editor: {
    border: "1.5px solid black",
    borderRadius: "12px",
    marginTop: "16px",
    marginBottom: "24px",
    padding: "14px",
    fontSize: "24px",
    flex: 1,
    minHeight: "350px",
    maxHeight: "calc(100vh - 400px)",
    overflowY: "auto",
    backgroundColor: "#ffffff",
    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
    transition: "all 0.2s ease",
    lineHeight: "1.8",
    "&:focus": {
      borderColor: "#3b82f6",
      outline: "none",
    },
  },
  checkButton: {
    backgroundColor: "#3b82f6",
    color: "white",
    padding: "16px 32px",
    fontSize: "18px",
    fontWeight: "600",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#2563eb",
      transform: "translateY(-1px)",
    },
    "&:active": {
      transform: "translateY(0)",
    },
  },
  clearButton: {
    backgroundColor: "white",
    color: "#dc3545",
    padding: "8px 12px",
    fontSize: "16px",
    fontWeight: "500",
    border: "#dc3545 solid 2px",
    borderRadius: "4px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.2s ease",
  },
} as const; 