export const styles = {
  container: {
    height: "100vh",
    minHeight: "100vh",
    width: "900px",
    padding: "48px 0",
    position: "relative" as const,
  },
  content: {
    maxWidth: "800px",
    margin: "0 auto",
    padding: "0 16px",
  },
  title: {
    fontSize: "38px",
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: "32px",
  },
  editor: {
    border: "1px solid #008fee",
    borderRadius: "4px",
    marginTop: "16px",
    marginBottom: "10px",
    padding: "8px",
    fontSize: "24px",
    minHeight: "300px",
  },
  checkButton: {
    backgroundColor: "#008fee",
    color: "white",
    padding: "12px 24px",
    fontSize: "18px",
    fontWeight: "bold",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
  clearButton: {
    backgroundColor: "white",
    color: "#dc3545",
    padding: "6px 10px",
    fontSize: "6px",
    fontWeight: "500",
    border: "#dc3545 solid 2px",
    borderRadius: "4px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    transition: "all 0.2s ease",
  },
} as const; 