export const LANGUAGE_OPTIONS = [
  { label: "Afrikaans", value: "af_ZA" },
  { label: "Akan", value: "ak_GH" },
  { label: "Albanian", value: "sq_AL" },
  { label: "Amharic", value: "am_ET" },
  { label: "Arabic (Moz)", value: "ar-moz" },
  { label: "Arabic (Ooe)", value: "ar-ooe" },
  { label: "Arabic (Ooe-2)", value: "ar-ooe-2" },
  { label: "Aragonese", value: "an_ES" },
  { label: "Armenian", value: "hy_AM" },
  { label: "Azerbaijani (Latin)", value: "az_AZ-latin" },
  { label: "Basque", value: "eu" },
  { label: "Belarusian", value: "be" },
  { label: "Belarusian (BY)", value: "be_BY" },
  { label: "Belarusian (Classic)", value: "be_classic" },
  { label: "Bengali", value: "bn_BD" },
  { label: "Breton", value: "br_FR" },
  { label: "Bulgarian", value: "bg_BG" },
  { label: "Burmese", value: "my_MW" },
  { label: "Catalan", value: "ca_ES" },
  { label: "Catalan (Valencia)", value: "ca_ES_valencia" },
  { label: "Coptic", value: "cop_EG" },
  { label: "Croatian", value: "hr_HR" },
  { label: "Czech", value: "cs" },
  { label: "Danish", value: "da_DK" },
  { label: "Dutch", value: "nl_NL" },
  { label: "English (Australia)", value: "en_AU" },
  { label: "English (Australia, Moz)", value: "en_AU-moz" },
  { label: "English (Canada)", value: "en_CA" },
  { label: "English (New Zealand)", value: "en_NZ" },
  { label: "English (South Africa)", value: "en_ZA" },
  { label: "English (UK)", value: "en_GB" },
  { label: "English (US)", value: "en_US" },
  { label: "Esperanto", value: "eo_EO" },
  { label: "Estonian", value: "et_EE" },
  { label: "Faroese", value: "fo_FO" },
  { label: "French", value: "fr" },
  { label: "Frisian", value: "fy_NL" },
  { label: "Friulian", value: "fur_IT" },
  { label: "Galician", value: "gl" },
  { label: "Gascon", value: "gsc_FR" },
  { label: "German (Austria)", value: "de_AT" },
  { label: "German (Austria, Frami Ooe)", value: "de_AT_frami-ooe" },
  { label: "German (Austria, Frami)", value: "de_AT_frami" },
  { label: "German (Germany)", value: "de_DE" },
  { label: "German (Germany, 1901 Ooe)", value: "de_DE-1901-ooe" },
  { label: "German (Germany, 1901)", value: "de_DE-1901" },
  { label: "German (Germany, Frami Ooe)", value: "de_DE_frami-ooe" },
  { label: "German (Germany, Moz)", value: "de_DE-moz" },
  { label: "German (Switzerland)", value: "de_CH" },
  { label: "German (Switzerland, Frami Ooe)", value: "de_CH_frami-ooe" },
  { label: "German (Switzerland, Frami)", value: "de_CH_frami" },
  { label: "German (Switzerland, Moz)", value: "de_CH-moz" },
  { label: "Greek", value: "el_GR" },
  { label: "Greek (Ooe)", value: "el_GR-ooe" },
  { label: "Gujarati", value: "gu_IN" },
  { label: "Hausa", value: "ha_GH" },
  { label: "Hebrew", value: "he_IL" },
  { label: "Hebrew (Moz)", value: "he_IL-moz" },
  { label: "Hebrew (Ooe)", value: "he_IL-ooe" },
  { label: "Hindi", value: "hi_IN" },
  { label: "Hungarian", value: "hu" },
  { label: "Icelandic", value: "is" },
  { label: "Indonesian", value: "id_ID" },
  { label: "Interlingua", value: "ia_ANY" },
  { label: "Irish", value: "ga_IE" },
  { label: "Italian", value: "it_IT" },
  { label: "Italian (Moz)", value: "it_IT-moz" },
  { label: "Italian (Ooe)", value: "it_IT-ooe" },
  { label: "Kannada", value: "kn_ID" },
  { label: "Kashubian", value: "csb_PL" },
  { label: "Kazakh", value: "kk" },
  { label: "Korean", value: "ko" },
  { label: "Kurdish", value: "ku_TR" },
  { label: "Latin (Ooe)", value: "la-ooe" },
  { label: "Latvian", value: "lv" },
  { label: "Lingala", value: "ln_CD" },
  { label: "Lithuanian", value: "lt" },
  { label: "Lower Sorbian", value: "dsb" },
  { label: "Malagasy", value: "mg_MG" },
  { label: "Malay", value: "ms_MY" },
  { label: "Maori", value: "mi_NZ" },
  { label: "Marathi", value: "mr_IN" },
  { label: "Marathi (Moz)", value: "mr_IN-moz" },
  { label: "Nepali", value: "ne_NP" },
  { label: "Norwegian Bokmål", value: "nb_NO" },
  { label: "Norwegian Nynorsk", value: "nn_NO" },
  { label: "Occitan", value: "oc_FR" },
  { label: "Odia", value: "or_IN" },
  { label: "Papiamento", value: "pap_AW" },
  { label: "Papiamento", value: "pap_CW" },
  { label: "Polish", value: "pl" },
  { label: "Portuguese (Brazil)", value: "pt_BR" },
  { label: "Portuguese (Portugal)", value: "pt_PT" },
  { label: "Punjabi", value: "pa_IN" },
  { label: "Romanian", value: "ro_RO" },
  { label: "Romanian (Classic)", value: "ro_RO-classic" },
  { label: "Russian", value: "ru" },
  { label: "Sanskrit", value: "sa_IN" },
  { label: "Scottish Gaelic", value: "gd_GB" },
  { label: "Slovak", value: "sk" },
  { label: "Slovenian (Ooe)", value: "sl_SI-ooe" },
  { label: "Spanish (Argentina)", value: "es_AR" },
  { label: "Spanish (Argentina, Moz)", value: "es_AR-moz" },
  { label: "Spanish (Bolivia)", value: "es_BO" },
  { label: "Spanish (Chile)", value: "es_CL" },
  { label: "Spanish (Colombia)", value: "es_CO" },
  { label: "Spanish (Costa Rica)", value: "es_CR" },
  { label: "Spanish (Cuba)", value: "es_CU" },
  { label: "Spanish (Dominican Republic)", value: "es_DO" },
  { label: "Spanish (Ecuador)", value: "es_EC" },
  { label: "Spanish (El Salvador)", value: "es_SV" },
  { label: "Spanish (Guatemala)", value: "es_GT" },
  { label: "Spanish (Honduras)", value: "es_HN" },
  { label: "Spanish (Mexico)", value: "es_MX" },
  { label: "Spanish (Mexico, Moz)", value: "es_MX-moz" },
  { label: "Spanish (Nicaragua)", value: "es_NI" },
  { label: "Spanish (Panama)", value: "es_PA" },
  { label: "Spanish (Paraguay)", value: "es_PY" },
  { label: "Spanish (Peru)", value: "es_PE" },
  { label: "Spanish (Puerto Rico)", value: "es_PR" },
  { label: "Spanish (Spain)", value: "es_ES" },
  { label: "Spanish (Spain, Moz)", value: "es_ES-moz" },
  { label: "Spanish (Uruguay)", value: "es_UY" },
  { label: "Spanish (Venezuela)", value: "es_VE" },
  { label: "Spanish (Venezuela, Moz)", value: "es_VE-moz" },
  { label: "Swahili", value: "sw" },
  { label: "Swedish", value: "sv_SE" },
  { label: "Tajik", value: "tg" },
  { label: "Tamil", value: "ta_TA" },
  { label: "Telugu", value: "te_IN" },
  { label: "Ukrainian", value: "uk" },
  { label: "Upper Sorbian", value: "hsb" },
  { label: "Welsh", value: "cy_GB" },
  { label: "Zulu", value: "zu_ZA" },
  { label: "sample language", value: "sample_code" }
] as const;

export const LANGUAGE_CODE_MAP: Record<string, string> = {
  af_ZA: 'af_ZA',
  ak_GH: 'ak_GH',
  am_ET: 'am_ET',
  an_ES: 'an_ES',
  'ar-moz': 'ar-moz',
  'ar-ooe': 'ar-ooe',
  'ar-ooe-2': 'ar-ooe-2',
  'az_AZ-latin': 'az_AZ-latin',
  be: 'be',
  be_BY: 'be_BY',
  be_classic: 'be_classic',
  bg_BG: 'bg_BG',
  bn_BD: 'bn_BD',
  br_FR: 'br_FR',
  ca_ES: 'ca_ES',
  ca_ES_valencia: 'ca_ES_valencia',
  cop_EG: 'cop_EG',
  cs: 'cs',
  csb_PL: 'csb_PL',
  cy_GB: 'cy_GB',
  da_DK: 'da_DK',
  de_AT: 'de_AT',
  de_AT_frami: 'de_AT_frami',
  'de_AT_frami-ooe': 'de_AT_frami-ooe',
  de_CH: 'de_CH',
  de_CH_frami: 'de_CH_frami',
  'de_CH_frami-ooe': 'de_CH_frami-ooe',
  'de_CH-moz': 'de_CH-moz',
  de_DE: 'de_DE',
  'de_DE_frami-ooe': 'de_DE_frami-ooe',
  'de_DE-1901': 'de_DE-1901',
  'de_DE-1901-ooe': 'de_DE-1901-ooe',
  'de_DE-moz': 'de_DE-moz',
  dsb: 'dsb',
  el_GR: 'el_GR',
  'el_GR-ooe': 'el_GR-ooe',
  en_AU: 'en_AU',
  'en_AU-moz': 'en_AU-moz',
  en_CA: 'en_CA',
  en_GB: 'en_GB',
  en_NZ: 'en_NZ',
  en_US: 'en_US',
  en_ZA: 'en_ZA',
  eo_EO: 'eo_EO',
  es_AR: 'es_AR',
  'es_AR-moz': 'es_AR-moz',
  es_BO: 'es_BO',
  es_CL: 'es_CL',
  es_CO: 'es_CO',
  es_CR: 'es_CR',
  es_CU: 'es_CU',
  es_DO: 'es_DO',
  es_EC: 'es_EC',
  es_ES: 'es_ES',
  'es_ES-moz': 'es_ES-moz',
  es_GT: 'es_GT',
  es_HN: 'es_HN',
  es_MX: 'es_MX',
  'es_MX-moz': 'es_MX-moz',
  es_NI: 'es_NI',
  es_PA: 'es_PA',
  es_PE: 'es_PE',
  es_PR: 'es_PR',
  es_PY: 'es_PY',
  es_SV: 'es_SV',
  es_UY: 'es_UY',
  es_VE: 'es_VE',
  'es_VE-moz': 'es_VE-moz',
  et_EE: 'et_EE',
  eu: 'eu',
  fo_FO: 'fo_FO',
  fr: 'fr',
  fur_IT: 'fur_IT',
  fy_NL: 'fy_NL',
  ga_IE: 'ga_IE',
  gd_GB: 'gd_GB',
  gl: 'gl',
  gsc_FR: 'gsc_FR',
  gu_IN: 'gu_IN',
  ha_GH: 'ha_GH',
  he_IL: 'he_IL',
  'he_IL-moz': 'he_IL-moz',
  'he_IL-ooe': 'he_IL-ooe',
  hi_IN: 'hi_IN',
  hr_HR: 'hr_HR',
  hsb: 'hsb',
  hu: 'hu',
  hy_AM: 'hy_AM',
  ia_ANY: 'ia_ANY',
  id_ID: 'id_ID',
  is: 'is',
  it_IT: 'it_IT',
  'it_IT-moz': 'it_IT-moz',
  'it_IT-ooe': 'it_IT-ooe',
  kk: 'kk',
  kn_ID: 'kn_ID',
  ko: 'ko',
  ku_TR: 'ku_TR',
  'la-ooe': 'la-ooe',
  ln_CD: 'ln_CD',
  lt: 'lt',
  lv: 'lv',
  mg_MG: 'mg_MG',
  mi_NZ: 'mi_NZ',
  mr_IN: 'mr_IN',
  'mr_IN-moz': 'mr_IN-moz',
  ms_MY: 'ms_MY',
  my_MW: 'my_MW',
  nb_NO: 'nb_NO',
  ne_NP: 'ne_NP',
  nl_NL: 'nl_NL',
  nn_NO: 'nn_NO',
  oc_FR: 'oc_FR',
  or_IN: 'or_IN',
  pa_IN: 'pa_IN',
  pap_AW: 'pap_AW',
  pap_CW: 'pap_CW',
  pl: 'pl',
  pt_BR: 'pt_BR',
  pt_PT: 'pt_PT',
  ro_RO: 'ro_RO',
  'ro_RO-classic': 'ro_RO-classic',
  ru: 'ru',
  sa_IN: 'sa_IN',
  sk: 'sk',
  'sl_SI-ooe': 'sl_SI-ooe',
  sq_AL: 'sq_AL',
  sv_SE: 'sv_SE',
  sw: 'sw',
  ta_TA: 'ta_TA',
  te_IN: 'te_IN',
  tg: 'tg',
  uk: 'uk',
  zu_ZA: 'zu_ZA',
  sample_code: 'sample_code'
};

export const SPECIAL_CHARACTERS: Record<string, string[]> = {
  af_ZA: [],
  ak_GH: [],
  am_ET: [],
  an_ES: [],
  'ar-moz': [],
  'ar-ooe': [],
  'ar-ooe-2': [],
  'az_AZ-latin': [],
  be: [],
  be_BY: [],
  be_classic: [],
  bg_BG: [],
  bn_BD: [],
  br_FR: [],
  ca_ES: [],
  ca_ES_valencia: [],
  cop_EG: [],
  cs: ["á", "č", "ď", "é", "ě", "í", "ň", "ó", "ř", "š", "ť", "ú", "ů", "ý", "ž", "Á", "Č", "Ď", "É", "Ě", "Í", "Ň", "Ó", "Ř", "Š", "Ť", "Ú", "Ů", "Ý", "Ž"],
  csb_PL: [],
  cy_GB: [],
  da_DK: ["æ", "ø", "å", "Æ", "Ø", "Å"],
  de_AT: ["ä", "ö", "ü", "ß", "Ä", "Ö", "Ü", "ẞ"],
  de_AT_frami: ["ä", "ö", "ü", "ß", "Ä", "Ö", "Ü", "ẞ"],
  'de_AT_frami-ooe': ["ä", "ö", "ü", "ß", "Ä", "Ö", "Ü", "ẞ"],
  de_CH: ["ä", "ö", "ü", "ß", "Ä", "Ö", "Ü", "ẞ"],
  de_CH_frami: ["ä", "ö", "ü", "ß", "Ä", "Ö", "Ü", "ẞ"],
  'de_CH_frami-ooe': ["ä", "ö", "ü", "ß", "Ä", "Ö", "Ü", "ẞ"],
  'de_CH-moz': ["ä", "ö", "ü", "ß", "Ä", "Ö", "Ü", "ẞ"],
  de_DE: ["ä", "ö", "ü", "ß", "Ä", "Ö", "Ü", "ẞ"],
  'de_DE_frami-ooe': ["ä", "ö", "ü", "ß", "Ä", "Ö", "Ü", "ẞ"],
  'de_DE-1901': ["ä", "ö", "ü", "ß", "Ä", "Ö", "Ü", "ẞ"],
  'de_DE-1901-ooe': ["ä", "ö", "ü", "ß", "Ä", "Ö", "Ü", "ẞ"],
  'de_DE-moz': ["ä", "ö", "ü", "ß", "Ä", "Ö", "Ü", "ẞ"],
  dsb: [],
  el_GR: [],
  'el_GR-ooe': [],
  en_AU: [],
  'en_AU-moz': [],
  en_CA: [],
  en_GB: [],
  en_NZ: [],
  en_US: [],
  en_ZA: [],
  eo_EO: [],
  es_AR: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  'es_AR-moz': ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_BO: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_CL: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_CO: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_CR: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_CU: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_DO: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_EC: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_ES: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  'es_ES-moz': ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_GT: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_HN: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_MX: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  'es_MX-moz': ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_NI: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_PA: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_PE: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_PR: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_PY: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_SV: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_UY: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  es_VE: ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  'es_VE-moz': ["á", "é", "í", "ó", "ú", "ñ", "ü", "Á", "É", "Í", "Ó", "Ú", "Ñ", "Ü", "¿", "¡"],
  et_EE: [],
  eu: [],
  fo_FO: [],
  fr: ["à", "â", "ç", "é", "è", "ê", "ë", "î", "ï", "ô", "ù", "û", "ü", "ÿ", "À", "Â", "Ç", "É", "È", "Ê", "Ë", "Î", "Ï", "Ô", "Ù", "Û", "Ü", "Ÿ"],
  fur_IT: [],
  fy_NL: [],
  ga_IE: [],
  gd_GB: [],
  gl: [],
  gsc_FR: [],
  gu_IN: [],
  ha_GH: [],
  he_IL: [],
  'he_IL-moz': [],
  'he_IL-ooe': [],
  hi_IN: [],
  hr_HR: [],
  hsb: [],
  hu: ["á", "é", "í", "ó", "ö", "ő", "ú", "ü", "ű", "Á", "É", "Í", "Ó", "Ö", "Ő", "Ú", "Ü", "Ű"],
  hy_AM: [],
  ia_ANY: [],
  id_ID: [],
  is: [],
  it_IT: ["à", "è", "é", "ì", "î", "ò", "ù", "À", "È", "É", "Ì", "Î", "Ò", "Ù"],
  'it_IT-moz': ["à", "è", "é", "ì", "î", "ò", "ù", "À", "È", "É", "Ì", "Î", "Ò", "Ù"],
  'it_IT-ooe': ["à", "è", "é", "ì", "î", "ò", "ù", "À", "È", "É", "Ì", "Î", "Ò", "Ù"],
  kk: [],
  kn_ID: [],
  ko: [],
  ku_TR: [],
  'la-ooe': [],
  ln_CD: [],
  lt: [],
  lv: [],
  mg_MG: [],
  mi_NZ: [],
  mr_IN: [],
  'mr_IN-moz': [],
  ms_MY: [],
  my_MW: [],
  nb_NO: [],
  ne_NP: [],
  nl_NL: ["é", "ë", "ï", "ó", "ö", "ü", "É", "Ë", "Ï", "Ó", "Ö", "Ü"],
  nn_NO: [],
  oc_FR: [],
  or_IN: [],
  pa_IN: [],
  pap_AW: [],
  pap_CW: [],
  pl: ["ą", "ć", "ę", "ł", "ń", "ó", "ś", "ź", "ż", "Ą", "Ć", "Ę", "Ł", "Ń", "Ó", "Ś", "Ź", "Ż"],
  pt_BR: ["á", "â", "ã", "ç", "é", "ê", "í", "ó", "ô", "õ", "ú", "Á", "Â", "Ã", "Ç", "É", "Ê", "Í", "Ó", "Ô", "Õ", "Ú"],
  pt_PT: ["á", "â", "ã", "ç", "é", "ê", "í", "ó", "ô", "õ", "ú", "Á", "Â", "Ã", "Ç", "É", "Ê", "Í", "Ó", "Ô", "Õ", "Ú"],
  ro_RO: ["ă", "â", "î", "ș", "ț", "Ă", "Â", "Î", "Ș", "Ț"],
  'ro_RO-classic': ["ă", "â", "î", "ș", "ț", "Ă", "Â", "Î", "Ș", "Ț"],
  ru: [],
  sa_IN: [],
  sk: [],
  'sl_SI-ooe': [],
  sq_AL: [],
  sv_SE: ["å", "ä", "ö", "Å", "Ä", "Ö"],
  sw: [],
  ta_TA: [],
  te_IN: [],
  tg: [],
  uk: [],
  zu_ZA: [],
  sample_code: []
};
