# Generated by Django 3.2.25 on 2024-11-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='currently_enrolled',
        ),
    ]
